// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFQ3RDgKJsLBP2-i7pSHrg3G6zzpJGtMU',
    appId: '1:808228391597:web:4cd49afc9245c324c2d424',
    messagingSenderId: '808228391597',
    projectId: 'rozliczacz-app',
    authDomain: 'rozliczacz-app.firebaseapp.com',
    storageBucket: 'rozliczacz-app.firebasestorage.app',
    measurementId: 'G-9CCB0QMC9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpNoaksIHKdke8H2D1EvEZQ4-hI9Zt28',
    appId: '1:808228391597:android:fb45ee186fe8de94c2d424',
    messagingSenderId: '808228391597',
    projectId: 'rozliczacz-app',
    storageBucket: 'rozliczacz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxcldHhlVovvDjlziHhcFvFuXUffi170',
    appId: '1:808228391597:ios:5a5de65b1ad37ae4c2d424',
    messagingSenderId: '808228391597',
    projectId: 'rozliczacz-app',
    storageBucket: 'rozliczacz-app.firebasestorage.app',
    iosBundleId: 'com.example.splitMoneyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKxcldHhlVovvDjlziHhcFvFuXUffi170',
    appId: '1:808228391597:ios:5a5de65b1ad37ae4c2d424',
    messagingSenderId: '808228391597',
    projectId: 'rozliczacz-app',
    storageBucket: 'rozliczacz-app.firebasestorage.app',
    iosBundleId: 'com.example.splitMoneyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFQ3RDgKJsLBP2-i7pSHrg3G6zzpJGtMU',
    appId: '1:808228391597:web:34e24861090076c4c2d424',
    messagingSenderId: '808228391597',
    projectId: 'rozliczacz-app',
    authDomain: 'rozliczacz-app.firebaseapp.com',
    storageBucket: 'rozliczacz-app.firebasestorage.app',
    measurementId: 'G-N98MWM64CX',
  );
}
